### ISSUE TITLE
修改文章详情页展示效果

### ISSUE THREAD

**Issue by limingth** [maodouio/mSaaS#6]
参考微信文章的风格

清华x-lab发布课程安排：[【活动】2016年清华x-lab《创业十堂课》火热开讲，小伙伴们速速报名](https://mp.weixin.qq.com/s?__biz=MzI2NjA4NTc1OQ==&mid=403403133&idx=2&sn=2eaceaf38bab4c8dbb601fa6c95f0e7b&scene=1&srcid=0330yheY0pTnHEkvkY8bQdS7&key=710a5d99946419d979165f4088d19af863288923bfd2052ddcd489dae55e3881590b1c5ef388809079147640c9353841&ascene=0&uin=ODU4OTAxMzIw&devicetype=iMac+MacBookAir6%2C1+OSX+OSX+10.10.5+build%2814F1605%29&version=11020201&pass_ticket=8oZG5gTbSY6jHRovDwQGJPjGWMa2LSfkzaOUeONlmCEtfn0qxi6lsmnTTTWgIy4M)

DNA基金发布讲座活动：[清华x-lab加速计划预热活动](https://mp.weixin.qq.com/s?__biz=MzI0ODE0NTc5Mw==&mid=405268263&idx=1&sn=64ff4de4a5eaee5a08f40794404d65a5&scene=1&srcid=0328edrGQMCmotcks1z4Ow0E&key=710a5d99946419d995a7fa7d2bda53c7c016217bfbddb6f75112d184befd9e8fe9b04c844413a46ef87d3546791a0a9c&ascene=0&uin=ODU4OTAxMzIw&devicetype=iMac+MacBookAir6%2C1+OSX+OSX+10.10.5+build%2814F1605%29&version=11020201&pass_ticket=8oZG5gTbSY6jHRovDwQGJPjGWMa2LSfkzaOUeONlmCEtfn0qxi6lsmnTTTWgIy4M)

亚杰商会发布项目计划：[“摇篮计划”十一期，等你续写传奇！](https://mp.weixin.qq.com/s?__biz=MjM5MzE3MzAyMA==&mid=401932534&idx=1&sn=fd629ee98e265b2539120ae268c6c124&scene=1&srcid=0328BWoOIdI8ONPFx7olul2t&key=710a5d99946419d94c876e1a6a5096716841ed4dd489c5ab320ce42b0dd95dbc6b2f2842879913f74ef961e4f68fe608&ascene=0&uin=ODU4OTAxMzIw&devicetype=iMac+MacBookAir6%2C1+OSX+OSX+10.10.5+build%2814F1605%29&version=11020201&pass_ticket=8oZG5gTbSY6jHRovDwQGJPjGWMa2LSfkzaOUeONlmCEtfn0qxi6lsmnTTTWgIy4M)

**Comment by roy2020china** [comment]
completed
